modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "aileron"
version = "${version}"
displayName = "Aileron"
authors = "Team Lodestar"
description = '''
A unique and expansive Elytra overhaul
'''
#logoFile = ""

[[dependencies.aileron]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aileron]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"